#include "utils.h"

namespace TestMemoryAccess
{

static const char *const g_names[] = { "None", "WorldStable", "This", "Owned", "Module", "Engine", "Program", "Unset" };

// Returns true on mismatch, after printing which function and what it got
static bool CheckAccess(asIScriptFunction *func, asEMemoryAccess read, asEMemoryAccess write, int line)
{
	if( func == 0 )
	{
		PRINTF("memory access: function not found (line %d)\n", line);
		return true;
	}
	asEMemoryAccess r = asMA_UNSET, w = asMA_UNSET;
	func->GetMemoryAccess(&r, &w);
	if( r != read || w != write )
	{
		PRINTF("memory access of '%s' is {%s, %s}, expected {%s, %s} (line %d)\n",
			func->GetDeclaration(true, true, true), g_names[r & 7], g_names[w & 7], g_names[read & 7], g_names[write & 7], line);
		return true;
	}
	return false;
}

#define EXPECT_ACCESS(func, read, write) if( CheckAccess((func), (read), (write), __LINE__) ) TEST_FAILED

static void NativeNoop() {}
static void NativeMethodNoop(void *) {}

static bool TestApi()
{
	bool fail = false;
	COutStream out;
	asIScriptEngine *engine = asCreateScriptEngine();
	engine->SetMessageCallback(asMETHOD(COutStream, Callback), &out, asCALL_THISCALL);

	int id = engine->RegisterGlobalFunction("void noop()", asFUNCTION(NativeNoop), asCALL_CDECL);
	if( id < 0 ) TEST_FAILED;
	asIScriptFunction *global = engine->GetFunctionById(id);

	// Undeclared natives report Unset
	EXPECT_ACCESS(global, asMA_UNSET, asMA_UNSET);

	if( global->SetMemoryAccess(asMA_NONE, asMA_NONE) < 0 ) TEST_FAILED;
	EXPECT_ACCESS(global, asMA_NONE, asMA_NONE);

	// A function without an object cannot touch one
	if( global->SetMemoryAccess(asMA_THIS, asMA_NONE) != asINVALID_ARG ) TEST_FAILED;
	if( global->SetMemoryAccess(asMA_NONE, asMA_OWNED) != asINVALID_ARG ) TEST_FAILED;
	// Unset is not declarable, and nothing writes world-stable state while the VM runs
	if( global->SetMemoryAccess(asMA_UNSET, asMA_NONE) != asINVALID_ARG ) TEST_FAILED;
	if( global->SetMemoryAccess(asMA_NONE, asMA_WORLD_STABLE) != asINVALID_ARG ) TEST_FAILED;
	// A rejected call leaves the previous declaration in place
	EXPECT_ACCESS(global, asMA_NONE, asMA_NONE);

	if( global->SetMemoryAccess(asMA_WORLD_STABLE, asMA_PROGRAM) < 0 ) TEST_FAILED;
	EXPECT_ACCESS(global, asMA_WORLD_STABLE, asMA_PROGRAM);

	engine->RegisterObjectType("NoCount", 0, asOBJ_REF | asOBJ_NOCOUNT);
	id = engine->RegisterObjectMethod("NoCount", "void m()", asFUNCTION(NativeMethodNoop), asCALL_CDECL_OBJLAST);
	asIScriptFunction *method = engine->GetFunctionById(id);
	if( method->SetMemoryAccess(asMA_THIS, asMA_OWNED) < 0 ) TEST_FAILED;
	EXPECT_ACCESS(method, asMA_THIS, asMA_OWNED);

	// Script functions are inferred, never declared
	asIScriptModule *mod = engine->GetModule("api", asGM_ALWAYS_CREATE);
	mod->AddScriptSection("api", "void s() {}");
	if( mod->Build() < 0 ) TEST_FAILED;
	asIScriptFunction *script = mod->GetFunctionByDecl("void s()");
	if( script == 0 || script->SetMemoryAccess(asMA_NONE, asMA_NONE) != asNOT_SUPPORTED ) TEST_FAILED;

	engine->ShutDownAndRelease();
	return fail;
}

static void TmplCallbackGeneric(asIScriptGeneric *gen)
{
	gen->SetReturnByte(1);
}
static void TmplFactoryGeneric(asIScriptGeneric *gen)
{
	gen->SetReturnAddress(0);
}
static void TmplNoopGeneric(asIScriptGeneric *)
{
}

// Template instances and factory stubs are generated by the engine, and must carry
// the scopes declared on the template's own methods and factory
static bool TestTemplateInheritance()
{
	bool fail = false;
	COutStream out;
	asIScriptEngine *engine = asCreateScriptEngine();
	engine->SetMessageCallback(asMETHOD(COutStream, Callback), &out, asCALL_THISCALL);

	if( engine->RegisterObjectType("tmpl<class T>", 0, asOBJ_REF | asOBJ_TEMPLATE) < 0 ) TEST_FAILED;
	if( engine->RegisterObjectBehaviour("tmpl<T>", asBEHAVE_TEMPLATE_CALLBACK, "bool f(int&in, bool&out)", asFUNCTION(TmplCallbackGeneric), asCALL_GENERIC) < 0 ) TEST_FAILED;
	int factoryId = engine->RegisterObjectBehaviour("tmpl<T>", asBEHAVE_FACTORY, "tmpl<T>@ f(int&in)", asFUNCTION(TmplFactoryGeneric), asCALL_GENERIC);
	if( factoryId < 0 ) TEST_FAILED;
	if( engine->RegisterObjectBehaviour("tmpl<T>", asBEHAVE_ADDREF, "void f()", asFUNCTION(TmplNoopGeneric), asCALL_GENERIC) < 0 ) TEST_FAILED;
	if( engine->RegisterObjectBehaviour("tmpl<T>", asBEHAVE_RELEASE, "void f()", asFUNCTION(TmplNoopGeneric), asCALL_GENERIC) < 0 ) TEST_FAILED;
	int methodId = engine->RegisterObjectMethod("tmpl<T>", "void set(const T &in)", asFUNCTION(TmplNoopGeneric), asCALL_GENERIC);
	if( methodId < 0 ) TEST_FAILED;

	if( factoryId >= 0 && engine->GetFunctionById(factoryId)->SetMemoryAccess(asMA_WORLD_STABLE, asMA_NONE) < 0 ) TEST_FAILED;
	if( methodId >= 0 && engine->GetFunctionById(methodId)->SetMemoryAccess(asMA_THIS, asMA_THIS) < 0 ) TEST_FAILED;

	asIScriptModule *mod = engine->GetModule("tmpl", asGM_ALWAYS_CREATE);
	mod->AddScriptSection("tmpl", "tmpl<int> @t;");
	if( mod->Build() < 0 ) TEST_FAILED;

	asITypeInfo *inst = engine->GetTypeInfoByDecl("tmpl<int>");
	if( inst == 0 )
	{
		TEST_FAILED;
	}
	else
	{
		EXPECT_ACCESS(inst->GetMethodByDecl("void set(const int &in)"), asMA_THIS, asMA_THIS);
		EXPECT_ACCESS(inst->GetFactoryByIndex(0), asMA_WORLD_STABLE, asMA_NONE);
	}

	engine->ShutDownAndRelease();
	return fail;
}

// The engine's own registrations must not leave Unset behind for hosts to trip on.
// This checks every built-in is declared, not that each declaration is right.
static bool TestEngineBuiltins()
{
	bool fail = false;
	asIScriptEngine *engine = asCreateScriptEngine();
	for( int id = 0; id <= engine->GetLastFunctionId(); id++ )
	{
		asIScriptFunction *f = engine->GetFunctionById(id);
		if( f == 0 || f->GetFuncType() != asFUNC_SYSTEM )
		{
			continue;
		}
		asEMemoryAccess r, w;
		f->GetMemoryAccess(&r, &w);
		if( r == asMA_UNSET || w == asMA_UNSET )
		{
			PRINTF("engine built-in '%s' (id %d) is undeclared\n", f->GetDeclaration(true, true, true), id);
			TEST_FAILED;
		}
	}
	engine->ShutDownAndRelease();
	return fail;
}

static asIScriptEngine *CreateEngine(COutStream &out)
{
	asIScriptEngine *engine = asCreateScriptEngine();
	engine->SetMessageCallback(asMETHOD(COutStream, Callback), &out, asCALL_THISCALL);
	return engine;
}

static asIScriptModule *BuildModule(asIScriptEngine *engine, const char *name, const char *code)
{
	asIScriptModule *mod = engine->GetModule(name, asGM_ALWAYS_CREATE);
	mod->AddScriptSection(name, code);
	if( mod->Build() < 0 )
	{
		PRINTF("module '%s' failed to build\n", name);
		return 0;
	}
	return mod;
}

static bool TestFrameLocal()
{
	bool fail = false;
	COutStream out;
	asIScriptEngine *engine = CreateEngine(out);
	asIScriptModule *mod = BuildModule(engine, "frame",
		"int add(int a, int b) { int c = a + b; return c * 2; } \n"
		"void loop() { for( int i = 0; i < 10; i++ ) {} } \n"
		"int fact(int n) { if( n <= 1 ) return 1; return n * fact(n - 1); } \n"
		"int even(int n) { if( n == 0 ) return 1; return odd(n - 1); } \n"
		"int odd(int n) { if( n == 0 ) return 0; return even(n - 1); } \n"
		"double conv(int a) { float f = a; return f * 2.0; } \n");
	if( mod == 0 )
	{
		TEST_FAILED;
	}
	else
	{
		EXPECT_ACCESS(mod->GetFunctionByDecl("int add(int, int)"), asMA_NONE, asMA_NONE);
		EXPECT_ACCESS(mod->GetFunctionByDecl("void loop()"), asMA_NONE, asMA_NONE);
#if 0 // enabled by Task 6
		EXPECT_ACCESS(mod->GetFunctionByDecl("int fact(int)"), asMA_NONE, asMA_NONE);
#endif
#if 0 // enabled by Task 6
		EXPECT_ACCESS(mod->GetFunctionByDecl("int even(int)"), asMA_NONE, asMA_NONE);
#endif
#if 0 // enabled by Task 6
		EXPECT_ACCESS(mod->GetFunctionByDecl("int odd(int)"), asMA_NONE, asMA_NONE);
#endif
		EXPECT_ACCESS(mod->GetFunctionByDecl("double conv(int)"), asMA_NONE, asMA_NONE);
	}
	engine->ShutDownAndRelease();
	return fail;
}

// A function using an opcode the scanner does not model yet must come out as
// Program, never as something narrower. Task 4 makes this function precise;
// this test then moves to its final expectation there.
static bool TestFailsClosed()
{
	bool fail = false;
	COutStream out;
	asIScriptEngine *engine = CreateEngine(out);
	asIScriptModule *mod = BuildModule(engine, "closed",
		"class C { int x; int get() { return x; } } \n");
	if( mod == 0 )
	{
		TEST_FAILED;
	}
	else
	{
		asITypeInfo *c = mod->GetTypeInfoByName("C");
		EXPECT_ACCESS(c->GetMethodByDecl("int get()"), asMA_PROGRAM, asMA_PROGRAM);
	}
	engine->ShutDownAndRelease();
	return fail;
}

bool Test()
{
	bool fail = false;
	if( TestApi() ) fail = true;
	if( TestTemplateInheritance() ) fail = true;
	if( TestEngineBuiltins() ) fail = true;
	if( TestFrameLocal() ) fail = true;
	if( TestFailsClosed() ) fail = true;
	return fail;
}

} // namespace TestMemoryAccess
