#include "utils.h"

namespace TestMemoryAccess
{

static const char *const g_names[] = { "None", "WorldStable", "This", "Owned", "Module", "Engine", "Program", "Unset" };

// Returns true on mismatch, after printing which function and what it got
static bool CheckAccess(asIScriptFunction *func, asEMemoryAccess read, asEMemoryAccess write, int line)
{
	if( func == 0 )
	{
		PRINTF("memory access: function not found (line %d)\n", line);
		return true;
	}
	asEMemoryAccess r = asMA_UNSET, w = asMA_UNSET;
	func->GetMemoryAccess(&r, &w);
	if( r != read || w != write )
	{
		PRINTF("memory access of '%s' is {%s, %s}, expected {%s, %s} (line %d)\n",
			func->GetDeclaration(true, true, true), g_names[r & 7], g_names[w & 7], g_names[read & 7], g_names[write & 7], line);
		return true;
	}
	return false;
}

#define EXPECT_ACCESS(func, read, write) if( CheckAccess((func), (read), (write), __LINE__) ) TEST_FAILED

static void NativeNoop() {}
static void NativeMethodNoop(void *) {}

static bool TestApi()
{
	bool fail = false;
	COutStream out;
	asIScriptEngine *engine = asCreateScriptEngine();
	engine->SetMessageCallback(asMETHOD(COutStream, Callback), &out, asCALL_THISCALL);

	int id = engine->RegisterGlobalFunction("void noop()", asFUNCTION(NativeNoop), asCALL_CDECL);
	if( id < 0 ) TEST_FAILED;
	asIScriptFunction *global = engine->GetFunctionById(id);

	// Undeclared natives report Unset
	EXPECT_ACCESS(global, asMA_UNSET, asMA_UNSET);

	if( global->SetMemoryAccess(asMA_NONE, asMA_NONE) < 0 ) TEST_FAILED;
	EXPECT_ACCESS(global, asMA_NONE, asMA_NONE);

	// A function without an object cannot touch one
	if( global->SetMemoryAccess(asMA_THIS, asMA_NONE) != asINVALID_ARG ) TEST_FAILED;
	if( global->SetMemoryAccess(asMA_NONE, asMA_OWNED) != asINVALID_ARG ) TEST_FAILED;
	// Unset is not declarable, and nothing writes world-stable state while the VM runs
	if( global->SetMemoryAccess(asMA_UNSET, asMA_NONE) != asINVALID_ARG ) TEST_FAILED;
	if( global->SetMemoryAccess(asMA_NONE, asMA_WORLD_STABLE) != asINVALID_ARG ) TEST_FAILED;
	// A rejected call leaves the previous declaration in place
	EXPECT_ACCESS(global, asMA_NONE, asMA_NONE);

	if( global->SetMemoryAccess(asMA_WORLD_STABLE, asMA_PROGRAM) < 0 ) TEST_FAILED;
	EXPECT_ACCESS(global, asMA_WORLD_STABLE, asMA_PROGRAM);

	engine->RegisterObjectType("NoCount", 0, asOBJ_REF | asOBJ_NOCOUNT);
	id = engine->RegisterObjectMethod("NoCount", "void m()", asFUNCTION(NativeMethodNoop), asCALL_CDECL_OBJLAST);
	asIScriptFunction *method = engine->GetFunctionById(id);
	if( method->SetMemoryAccess(asMA_THIS, asMA_OWNED) < 0 ) TEST_FAILED;
	EXPECT_ACCESS(method, asMA_THIS, asMA_OWNED);

	// Script functions are inferred, never declared
	asIScriptModule *mod = engine->GetModule("api", asGM_ALWAYS_CREATE);
	mod->AddScriptSection("api", "void s() {}");
	if( mod->Build() < 0 ) TEST_FAILED;
	asIScriptFunction *script = mod->GetFunctionByDecl("void s()");
	if( script == 0 || script->SetMemoryAccess(asMA_NONE, asMA_NONE) != asNOT_SUPPORTED ) TEST_FAILED;

	engine->ShutDownAndRelease();
	return fail;
}

static void TmplCallbackGeneric(asIScriptGeneric *gen)
{
	gen->SetReturnByte(1);
}
static void TmplFactoryGeneric(asIScriptGeneric *gen)
{
	gen->SetReturnAddress(0);
}
static void TmplNoopGeneric(asIScriptGeneric *)
{
}

// Template instances and factory stubs are generated by the engine, and must carry
// the scopes declared on the template's own methods and factory
static bool TestTemplateInheritance()
{
	bool fail = false;
	COutStream out;
	asIScriptEngine *engine = asCreateScriptEngine();
	engine->SetMessageCallback(asMETHOD(COutStream, Callback), &out, asCALL_THISCALL);

	if( engine->RegisterObjectType("tmpl<class T>", 0, asOBJ_REF | asOBJ_TEMPLATE) < 0 ) TEST_FAILED;
	if( engine->RegisterObjectBehaviour("tmpl<T>", asBEHAVE_TEMPLATE_CALLBACK, "bool f(int&in, bool&out)", asFUNCTION(TmplCallbackGeneric), asCALL_GENERIC) < 0 ) TEST_FAILED;
	int factoryId = engine->RegisterObjectBehaviour("tmpl<T>", asBEHAVE_FACTORY, "tmpl<T>@ f(int&in)", asFUNCTION(TmplFactoryGeneric), asCALL_GENERIC);
	if( factoryId < 0 ) TEST_FAILED;
	if( engine->RegisterObjectBehaviour("tmpl<T>", asBEHAVE_ADDREF, "void f()", asFUNCTION(TmplNoopGeneric), asCALL_GENERIC) < 0 ) TEST_FAILED;
	if( engine->RegisterObjectBehaviour("tmpl<T>", asBEHAVE_RELEASE, "void f()", asFUNCTION(TmplNoopGeneric), asCALL_GENERIC) < 0 ) TEST_FAILED;
	int methodId = engine->RegisterObjectMethod("tmpl<T>", "void set(const T &in)", asFUNCTION(TmplNoopGeneric), asCALL_GENERIC);
	if( methodId < 0 ) TEST_FAILED;

	if( factoryId >= 0 && engine->GetFunctionById(factoryId)->SetMemoryAccess(asMA_WORLD_STABLE, asMA_NONE) < 0 ) TEST_FAILED;
	if( methodId >= 0 && engine->GetFunctionById(methodId)->SetMemoryAccess(asMA_THIS, asMA_THIS) < 0 ) TEST_FAILED;

	asIScriptModule *mod = engine->GetModule("tmpl", asGM_ALWAYS_CREATE);
	mod->AddScriptSection("tmpl", "tmpl<int> @t;");
	if( mod->Build() < 0 ) TEST_FAILED;

	asITypeInfo *inst = engine->GetTypeInfoByDecl("tmpl<int>");
	if( inst == 0 )
	{
		TEST_FAILED;
	}
	else
	{
		EXPECT_ACCESS(inst->GetMethodByDecl("void set(const int &in)"), asMA_THIS, asMA_THIS);
		EXPECT_ACCESS(inst->GetFactoryByIndex(0), asMA_WORLD_STABLE, asMA_NONE);
	}

	engine->ShutDownAndRelease();
	return fail;
}

// The engine's own registrations must not leave Unset behind for hosts to trip on.
// This checks every built-in is declared, not that each declaration is right.
static bool TestEngineBuiltins()
{
	bool fail = false;
	asIScriptEngine *engine = asCreateScriptEngine();
	for( int id = 0; id <= engine->GetLastFunctionId(); id++ )
	{
		asIScriptFunction *f = engine->GetFunctionById(id);
		if( f == 0 || f->GetFuncType() != asFUNC_SYSTEM )
		{
			continue;
		}
		asEMemoryAccess r, w;
		f->GetMemoryAccess(&r, &w);
		if( r == asMA_UNSET || w == asMA_UNSET )
		{
			PRINTF("engine built-in '%s' (id %d) is undeclared\n", f->GetDeclaration(true, true, true), id);
			TEST_FAILED;
		}
	}
	engine->ShutDownAndRelease();
	return fail;
}

static asIScriptEngine *CreateEngine(COutStream &out)
{
	asIScriptEngine *engine = asCreateScriptEngine();
	engine->SetMessageCallback(asMETHOD(COutStream, Callback), &out, asCALL_THISCALL);
	return engine;
}

static asIScriptModule *BuildModule(asIScriptEngine *engine, const char *name, const char *code)
{
	asIScriptModule *mod = engine->GetModule(name, asGM_ALWAYS_CREATE);
	mod->AddScriptSection(name, code);
	if( mod->Build() < 0 )
	{
		PRINTF("module '%s' failed to build\n", name);
		return 0;
	}
	return mod;
}

static bool TestFrameLocal()
{
	bool fail = false;
	COutStream out;
	asIScriptEngine *engine = CreateEngine(out);
	asIScriptModule *mod = BuildModule(engine, "frame",
		"int add(int a, int b) { int c = a + b; return c * 2; } \n"
		"void loop() { for( int i = 0; i < 10; i++ ) {} } \n"
		"int fact(int n) { if( n <= 1 ) return 1; return n * fact(n - 1); } \n"
		"int even(int n) { if( n == 0 ) return 1; return odd(n - 1); } \n"
		"int odd(int n) { if( n == 0 ) return 0; return even(n - 1); } \n"
		"double conv(int a) { float f = a; return f * 2.0; } \n");
	if( mod == 0 )
	{
		TEST_FAILED;
	}
	else
	{
		EXPECT_ACCESS(mod->GetFunctionByDecl("int add(int, int)"), asMA_NONE, asMA_NONE);
		EXPECT_ACCESS(mod->GetFunctionByDecl("void loop()"), asMA_NONE, asMA_NONE);
#if 0 // enabled by Task 6
		EXPECT_ACCESS(mod->GetFunctionByDecl("int fact(int)"), asMA_NONE, asMA_NONE);
#endif
#if 0 // enabled by Task 6
		EXPECT_ACCESS(mod->GetFunctionByDecl("int even(int)"), asMA_NONE, asMA_NONE);
#endif
#if 0 // enabled by Task 6
		EXPECT_ACCESS(mod->GetFunctionByDecl("int odd(int)"), asMA_NONE, asMA_NONE);
#endif
		EXPECT_ACCESS(mod->GetFunctionByDecl("double conv(int)"), asMA_NONE, asMA_NONE);
	}
	engine->ShutDownAndRelease();
	return fail;
}

// Members are reached through `this`, an owned member object is Owned, anything
// reached through a handle is Program, and each parameter kind starts from its
// own scope (spec 2.1)
static bool TestThisAndFields()
{
	bool fail = false;
	COutStream out;
	asIScriptEngine *engine = CreateEngine(out);
	asIScriptModule *mod = BuildModule(engine, "fields",
		"class In { int v; } \n"
		"class C \n"
		"{ \n"
		"  int x; \n"
		"  In inner; \n"
		"  In@ h; \n"
		"  int get() { return x; } \n"
		"  int getX() { return x; } \n"
		"  void setX() { x = 1; } \n"
		"  void setInner() { inner.v = 1; } \n"
		"  int getInner() { return inner.v; } \n"
		"  void setH() { h.v = 1; } \n"
		"  void tern(bool c) { int a = 0; int b = 0; (c ? a : b) = 5; x = a; } \n"
		"  int readRef(int a, const In &in o) { return o.v; } \n"
		"  void writeOut(int a, In &out o) { o.v = 1; } \n"
		"} \n"
		"void outParam(int &out o) { o = 1; } \n"
		"void inoutParam(In &inout o) { o.v = 1; } \n"
		"int constIn(const In &in o) { return o.v; } \n"
		"int byValueIn(In &in o) { return o.v; } \n");
	if( mod == 0 )
	{
		TEST_FAILED;
	}
	else
	{
		asITypeInfo *c = mod->GetTypeInfoByName("C");
		if( c == 0 )
		{
			TEST_FAILED;
		}
		else
		{
			EXPECT_ACCESS(c->GetMethodByDecl("int get()"), asMA_THIS, asMA_NONE);
			EXPECT_ACCESS(c->GetMethodByDecl("int getX()"), asMA_THIS, asMA_NONE);
			EXPECT_ACCESS(c->GetMethodByDecl("void setX()"), asMA_NONE, asMA_THIS);
			// Loading the member pointer reads `this`; the member object is Owned
			EXPECT_ACCESS(c->GetMethodByDecl("void setInner()"), asMA_THIS, asMA_OWNED);
			EXPECT_ACCESS(c->GetMethodByDecl("int getInner()"), asMA_OWNED, asMA_NONE);
			// Anything reached through a handle is Program
			EXPECT_ACCESS(c->GetMethodByDecl("void setH()"), asMA_THIS, asMA_PROGRAM);
			// The two paths select different frame slots, so the write may have
			// changed any slot, `this` included, and the member write is Program
			EXPECT_ACCESS(c->GetMethodByDecl("void tern(bool)"), asMA_NONE, asMA_PROGRAM);
			// Parameters off offset 0 reach their fields through LoadRObjR
			EXPECT_ACCESS(c->GetMethodByDecl("int readRef(int, const In&in)"), asMA_PROGRAM, asMA_NONE);
			EXPECT_ACCESS(c->GetMethodByDecl("void writeOut(int, In&out)"), asMA_NONE, asMA_NONE);
		}
		EXPECT_ACCESS(mod->GetFunctionByDecl("void outParam(int&out)"), asMA_NONE, asMA_NONE);
		EXPECT_ACCESS(mod->GetFunctionByDecl("void inoutParam(In&inout)"), asMA_NONE, asMA_PROGRAM);
		// The compiler passes a const &in object without copying it (spec 2.1)
		EXPECT_ACCESS(mod->GetFunctionByDecl("int constIn(const In&in)"), asMA_PROGRAM, asMA_NONE);
		// A non-const &in is the caller's copy
		EXPECT_ACCESS(mod->GetFunctionByDecl("int byValueIn(In&in)"), asMA_NONE, asMA_NONE);
	}
	engine->ShutDownAndRelease();
	return fail;
}

// The method as a host sees it, or 0 (which CheckAccess reports) when the type is missing
static asIScriptFunction *MethodOf(asIScriptModule *mod, const char *typeName, const char *decl)
{
	asITypeInfo *type = mod ? mod->GetTypeInfoByName(typeName) : 0;
	if( type == 0 )
	{
		PRINTF("type '%s' not found\n", typeName);
		return 0;
	}
	return type->GetMethodByDecl(decl);
}

// A virtual or interface entry is the join over every body a call through it can reach
static bool TestDispatch()
{
	bool fail = false;
	COutStream out;
	asIScriptEngine *engine = CreateEngine(out);

	// D's override writes a global, which no task so far models, so the join reaches
	// Program (Task 5 moves it to {None, Module}); E has a single frame-local body,
	// which shows the narrowing path is live
	asIScriptModule *mod = BuildModule(engine, "overrides",
		"int gx; \n"
		"class B { int f(int a) { return a + 1; } } \n"
		"class D : B { int f(int a) override { gx = a; return a; } } \n"
		"class E { int g(int a) { return a; } } \n");
	if( mod == 0 )
	{
		TEST_FAILED;
	}
	else
	{
		EXPECT_ACCESS(MethodOf(mod, "E", "int g(int)"), asMA_NONE, asMA_NONE);
		EXPECT_ACCESS(MethodOf(mod, "B", "int f(int)"), asMA_PROGRAM, asMA_PROGRAM);
	}

	// A module built later can add implementations of a shared type
	mod = BuildModule(engine, "shared",
		"shared class S { int h(int a) { return a; } } \n");
	if( mod == 0 )
	{
		TEST_FAILED;
	}
	else
	{
		EXPECT_ACCESS(MethodOf(mod, "S", "int h(int)"), asMA_PROGRAM, asMA_PROGRAM);
	}

	// Q writes a global, which no task so far models (Task 5 moves I::k to {None, Module})
	mod = BuildModule(engine, "interface",
		"int gy; \n"
		"interface I { int k(int a); } \n"
		"class P : I { int k(int a) { return a; } } \n"
		"class Q : I { int k(int a) { gy = a; return a; } } \n");
	if( mod == 0 )
	{
		TEST_FAILED;
	}
	else
	{
		EXPECT_ACCESS(MethodOf(mod, "I", "int k(int)"), asMA_PROGRAM, asMA_PROGRAM);
		EXPECT_ACCESS(MethodOf(mod, "P", "int k(int)"), asMA_NONE, asMA_NONE);
	}

	// A member read in one implementation lifts the entry to This, above P's None
	mod = BuildModule(engine, "interface4",
		"interface J { int k(int a); } \n"
		"class P2 : J { int k(int a) { return a; } } \n"
		"class Q2 : J { int y; int k(int a) { return y; } } \n");
	if( mod == 0 )
	{
		TEST_FAILED;
	}
	else
	{
		EXPECT_ACCESS(MethodOf(mod, "Q2", "int k(int)"), asMA_THIS, asMA_NONE);
		EXPECT_ACCESS(MethodOf(mod, "J", "int k(int)"), asMA_THIS, asMA_NONE);
	}

	// Without Q every implementation is frame-local
	mod = BuildModule(engine, "interface2",
		"interface I { int k(int a); } \n"
		"class P : I { int k(int a) { return a; } } \n");
	if( mod == 0 )
	{
		TEST_FAILED;
	}
	else
	{
		EXPECT_ACCESS(MethodOf(mod, "I", "int k(int)"), asMA_NONE, asMA_NONE);
	}

	// A derived interface is a module type that lists its base among its
	// interfaces but has no bodies and no vtable offsets of its own
	mod = BuildModule(engine, "interface3",
		"interface I1 { int k(int a); } \n"
		"interface I2 : I1 {} \n"
		"class R : I2 { int k(int a) { return a; } } \n");
	if( mod == 0 )
	{
		TEST_FAILED;
	}
	else
	{
		EXPECT_ACCESS(MethodOf(mod, "I1", "int k(int)"), asMA_NONE, asMA_NONE);
	}

	engine->ShutDownAndRelease();
	return fail;
}

// The public API does not expose a global's init function, so catch it while it runs
static void CaptureRunningFunction(asIScriptContext *ctx, void *param)
{
	asIScriptFunction **captured = (asIScriptFunction**)param;
	if( *captured == 0 && ctx->GetCallstackSize() > 0 )
	{
		*captured = ctx->GetFunction(0);
		if( *captured )
		{
			(*captured)->AddRef();
		}
	}
}

static asIScriptContext *RequestCapturingContext(asIScriptEngine *engine, void *param)
{
	asIScriptContext *ctx = engine->CreateContext();
	ctx->SetLineCallback(asFUNCTION(CaptureRunningFunction), param, asCALL_CDECL);
	return ctx;
}

static void ReturnCapturingContext(asIScriptEngine *, asIScriptContext *ctx, void *)
{
	ctx->Release();
}

// CompileGlobalVar adds an init function after the build, which must get computed scopes too
static bool TestCompileGlobalVar()
{
	bool fail = false;
	COutStream out;
	asIScriptEngine *engine = CreateEngine(out);
	asIScriptModule *mod = BuildModule(engine, "globals", "void f() {} \n");
	asIScriptFunction *initFunc = 0;
	if( mod == 0 )
	{
		TEST_FAILED;
	}
	else
	{
		engine->SetContextCallbacks(RequestCapturingContext, ReturnCapturingContext, &initFunc);
		if( mod->CompileGlobalVar("g2", "int g2 = 5;", 0) < 0 )
		{
			TEST_FAILED;
		}
		engine->SetContextCallbacks(0, 0, 0);
		if( initFunc == 0 )
		{
			PRINTF("the init function of g2 did not run\n");
			TEST_FAILED;
		}
		else
		{
			// The body is SUSPEND; SetG4 g2, 5; RET. Writing g2 makes the final
			// scope {None, Module}; until the global opcodes are modelled SetG4
			// fails closed. Either way it is computed, never Unset.
			EXPECT_ACCESS(initFunc, asMA_PROGRAM, asMA_PROGRAM);
			initFunc->Release();
		}
	}
	engine->ShutDownAndRelease();
	return fail;
}

bool Test()
{
	bool fail = false;
	if( TestApi() )
	{
		fail = true;
	}
	if( TestTemplateInheritance() )
	{
		fail = true;
	}
	if( TestEngineBuiltins() )
	{
		fail = true;
	}
	if( TestFrameLocal() )
	{
		fail = true;
	}
	if( TestThisAndFields() )
	{
		fail = true;
	}
	if( TestDispatch() )
	{
		fail = true;
	}
	if( TestCompileGlobalVar() )
	{
		fail = true;
	}
	return fail;
}

} // namespace TestMemoryAccess
